### ISSUE TITLE
在ThoughtWorks，你应该知道的Feedback

### ISSUE THREAD

**Issue by yuanshenjian** [yuanshenjian/yuanshenjian.github.io#2]
https://xp-bootcamp.org/feedback-in-thoughtworks/ 

 袁慎建, Yuan Shenjian, eXtreme Programming, 极限编程, , , 在ThoughtWorks，你应该知道的Feedback, , Career, 袁慎建的博客, ThoughtWorks, 文章, 博客, 袁慎建的博客, Feedback的特殊意义 Feedback为什么如此重要？ Feed...

**Comment by sjyuan-cc** [comment]
ThoughtWorks是一家非常适合热爱技术的人员的工作场所，有兴趣的小伙伴欢迎联系我~
