### ISSUE TITLE
ARCHIVE

### ISSUE THREAD

**Issue by yuanshenjian** [yuanshenjian/yuanshenjian.github.io#4]
https://xp-bootcamp.org/archives/ 

 袁慎建, Yuan Shenjian, eXtreme Programming, 极限编程, , , ARCHIVE, , , 袁慎建的博客, ThoughtWorks, 文章, 博客, 袁慎建的博客, {% for tag in site.tags %} {% assign t = tag...

**Comment by sjyuan-cc** [comment]
新增了左边的动态导航~

**Comment by sjyuan-cc** [comment]
读者如果对这个分类界面有什么建议，也反馈直接留言反馈
